config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:create, :new]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :movie
    belongs_to :list
    validates :comment, length: { minimum: 6 }
    validates :movie, presence: true
    validates :movie_id, uniqueness: { scope: :list_id, message: "and list pairing must be unique" }
end

app/models/list.rb
class List < ApplicationRecord
    has_many :bookmarks
    has_many :movies, through: :bookmarks
    validates :name, presence: true
    validates :name, presence: true, uniqueness: true
    has_many :movies, through: :bookmarks, dependent: :destroy
    has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :bookmarks
    validates :title, presence: true, uniqueness: true
    validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to_bookmark_path(@bookmark)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.set_bookmark
    Bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end
  
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
      if @list.save
        redirect_to list_path(@list)
      else
        render :new, status: :unprocessable_entity
      end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmarks</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.submit %>
  <%= f.association :movie, collection: @movies %>
<% end %>

<%= @bookmarks %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>My Lists</h1>

<% @lists.each do |list| %>
<p><%= list.name %></p>
<%= cl_image_tag list.photo.key if list.photo.attached? %>
<% end %>

<%= link_to "Create Another List", new_list_path %>

app/views/lists/new.html.erb
<h1>Create a List</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
  <%= f.input :photo, as: :file %>
<% end %>

app/views/lists/show.html.erb
<h1>Lists</h1>

<%= link_to "View List", lists_path %>
<%= @list.name %>